export const products = [
    {
      id: 1,
      title: "Original 25 watt Type C Fast",
      description: "White color",
      price: "200",
      img: "https://m.media-amazon.com/images/I/21To0ucR5pL.jpg",
      quantity: 1,
    },
    {
      id: 2,
      title: "Samsung M21",
      description: "Sky Blue color",
      price: "2300",
      img: "https://images.pexels.com/photos/47261/pexels-photo-47261.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=750&w=1260",
      quantity: 1,
    },
    {
      id: 3,
      title: "DIGI DECOR Apple Airpods Mobile Skin",
      description: "White color",
      price: "500",
      img: "https://rukminim1.flixcart.com/image/832/832/kmwcuq80/mobile-skin/o/m/5/mdsh-skin-apr2021-5388-mudshi-original-imagfpfu2zah5qzc.jpeg?q=70",
      quantity: 1,
    },
    {
      id: 4,
      title: "iPhone 13",
      description: "Best mobile ever",
      price: "9000",
      img: "https://store.storeimages.cdn-apple.com/4668/as-images.apple.com/is/iphone-13-finish-select-202207-6-1inch-blue_AV2?wid=5120&hei=2880&fmt=p-jpg&qlt=80&.v=1656712903762",
      quantity: 1,
    },
    {
      id: 5,
      title: "SAMSUNG Galaxy Z Flip3 5G",
      description: "black in color",
      price: "3500",
      img: "https://rukminim1.flixcart.com/image/832/832/ksnjp8w0/mobile/w/u/8/galaxy-z-flip3-5g-sm-f711bzeeinu-samsung-original-imag662adrayy6cg.jpeg?q=70",
      quantity: 1,
    },
    {
      id: 6,
      title: "WeCre8 Skin's Vivo Y20G Mobile Skin ",
      description: "black in color",
      price: "30",
      img: "https://rukminim1.flixcart.com/image/832/832/l4u7vrk0/mobile-skin/w/i/l/feeling-sad-mobile-back-skin-or-vinyl-wrap-for-vivo-y20g-mobile-original-imagfngtwgmjybgb.jpeg?q=70",
      quantity: 1,
    },
    {
      id: 7,
      title: "SAMSUNG Watch 4, 44mmSuper",
      description: "Best in Range",
      price: "3900",
      img: "https://rukminim1.flixcart.com/image/832/832/kst9gnk0/smartwatch/j/k/9/1-4-android-sm-r875fzgainu-samsung-yes-original-imag6axcsyt36y8v.jpeg?q=70",
      quantity: 1,
    },
    {
      id: 8,
      title: "Samsung Galaxy S21 5G",
      description: "black in color",
      price: "2500",
      img: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcTdvzguZMIE7pR4hMncsAXHJdVWHmb7xI5dY_AEdYSCzT8svMGnv0roUAKvYU7EPZbnqdvr7ARS_zkVFXfX3e7SuKHLBSMW",
      quantity: 1,
    },
  ];